export const directionData = [
	{
		title: 'Разработка мобильных приложений',
		icon: './phone.svg',
		to: 'mobiledev',
	},
	{
		title: 'Разработка и внедрение ERP систем',
		icon: './branch.svg',
		to: 'erpsystem',
	},
	{
		title: 'UI/UX дизайн',
		icon: 'layer.svg',
		to: 'uiuxdesign',
	},
	{
		title: 'IT консалтинг',
		icon: './computer.svg',
		to: 'itconsulting',
	},
	{
		title: 'Оптимизация инфроструктуры',
		icon: 'settings.svg',
		to: 'optimization',
	},
]

export const aboutUs = [
	{ title: 'Услуги', to: 'services' },
	{ title: 'Команда', to: 'team' },
	{ title: 'Инструменты', to: 'tools' },
	{ title: 'Клиенты', to: 'clients' },
]
export const services = [
	{ title: 'Разработка мобильных приложений', to: 'mobiledev' },
	{ title: 'Разработка и внедрение ERP систем', to: 'erpsystem' },
	{ title: 'UI / UX дизайн', to: 'uiuxdesign' },
	{ title: 'IT консалтинг', to: 'itconsulting' },
	{ title: 'Оптимизация инфраструктуры', to: 'optimization' },
]
export const portfolio = [
	{ title: 'Delever', to: 'delever', icon: './tools/delever-logo.svg' },
	{ title: 'Sms.uz', to: 'smsuz', icon: './tools/smsuzz-logo.svg' },
	{ title: 'Goodzone', to: 'goodzone', icon: './tools/goodzone-logo.svg' },
	{ title: 'Iman', to: 'iman', icon: './tools/iman-logo.svg' },
]

export const tools = [
	{ title: 'Promotheus', icon: './tools/tools01.svg', role: 'Infrastructure' },
	{ title: 'Loki', icon: './tools/tools02.svg', role: 'Infrastructure' },
	{ title: 'Bitbucket', icon: './tools/tools03.svg', role: 'Infrastructure' },
	{ title: 'Gitlab', icon: './tools/tools04.svg', role: 'Infrastructure' },
	{ title: 'Kotlin', icon: './tools/tools05.svg', role: 'Mobile' },
	{ title: 'Android', icon: './tools/tools06.svg', role: 'Mobile' },
	{ title: 'Java', icon: './tools/tools07.svg', role: 'Backend' },
	{ title: 'Azure', icon: './tools/tools08.svg', role: 'Infrastructure' },
	{ title: 'GCP', icon: './tools/tools09.svg', role: 'Infrastructure' },
	{
		title: 'DigitalOcean',
		icon: './tools/tools10.svg',
		role: 'Infrastructure',
	},
	{ title: 'AWS', icon: './tools/tools11.svg', role: 'Infrastructure' },
	{ title: 'Kubernetes', icon: './tools/tools12.svg', role: 'Infrastructure' },
	{ title: 'ELK', icon: './tools/tools13.svg', role: 'Infrastructure' },
	{ title: 'Grafana', icon: './tools/tools14.svg', role: 'Infrastructure' },
	{ title: 'Terraform', icon: './tools/tools15.svg', role: 'Devops' },
	{ title: 'IOS', icon: './tools/tools16.svg', role: 'Mobile' },
	{ title: 'Swift', icon: './tools/tools17.svg', role: 'Mobile' },
	{ title: 'Flutter', icon: './tools/tools47.svg', role: 'Mobile' },
	{ title: 'Next.JS', icon: './tools/tools18.svg', role: 'Frontend' },
	{ title: 'React.JS', icon: './tools/tools19.svg', role: 'Frontend' },
	{ title: 'Javascript', icon: './tools/tools20.svg', role: 'Frontend' },
	{ title: 'Balsamic', icon: './tools/tools21.svg', role: 'UX/UI' },
	{ title: 'Invision', icon: './tools/tools22.svg', role: 'UX/UI' },
	{ title: 'Figma', icon: './tools/tools23.svg', role: 'UX/UI' },
	{ title: 'Docker', icon: './tools/tools24.svg', role: 'Devops' },
	{ title: 'PostgreSQL', icon: './tools/tools25.svg', role: 'Backend' },
	{ title: 'Python', icon: './tools/tools26.svg', role: 'Backend' },
	{ title: 'Node.JS', icon: './tools/tools27.svg', role: 'Backend' },
	{ title: 'PHP', icon: './tools/tools28.svg', role: 'Backend' },
	{ title: 'GO', icon: './tools/tools29.svg', role: 'Backend' },
	{ title: 'Ant Design', icon: './tools/tools30.svg', role: 'Frontend' },
	{ title: 'Gatsby.JS', icon: './tools/tools31.png', role: 'Frontend' },
	{ title: 'Vue.JS', icon: './tools/tools32.svg', role: 'Frontend' },
	{ title: 'Principle', icon: './tools/tools33.svg', role: 'UX/UI' },
	{ title: 'Sketch', icon: './tools/tools34.svg', role: 'UX/UI' },
	{ title: 'Adobe suite', icon: './tools/tools35.svg', role: 'UX/UI' },
	{ title: 'YouTrack', icon: './tools/tools36.svg', role: 'Testing' },
	{ title: 'Appium', icon: './tools/tools37.svg', role: 'Testing' },
	{ title: 'Cypress', icon: './tools/tools38.svg', role: 'Testing' },
	{ title: 'Jmeter', icon: './tools/tools39.svg', role: 'Testing' },
	{ title: 'MongoDB', icon: './tools/tools40.svg', role: 'Backend' },
	{ title: 'Cassandra', icon: './tools/tools41.svg', role: 'Backend' },
	{ title: 'Sass', icon: './tools/tools42.svg', role: 'Frontend' },
	{ title: 'Material UI', icon: './tools/tools43.svg', role: 'Frontend' },
	{ title: 'Zeplin', icon: './tools/tools44.svg', role: 'UX/UI' },
	{ title: 'Illustrator', icon: './tools/tools45.svg', role: 'UX/UI' },
	{ title: 'Lottie', icon: './tools/tools48.svg', role: 'UX/UI' },
	{ title: 'Photoshop', icon: './tools/tools46.svg', role: 'UX/UI' },
]
